### ISSUE TITLE
TypeScript Conversion

### ISSUE THREAD

**Issue by pspeter3** [jorgebucaran/ultradom#7]
This looks really great. How would you feel about converting to TypeScript? (happy to help)

**Comment by jbucaran** [comment]
@pspeter3 Let's do it!

**Comment by jbucaran** [comment]
Ping @ngryman! 💪

**Comment by sumeetsarkar** [comment]
Sure! I will like to help too

**Comment by pspeter3** [comment]
Alright, I think that in order to convert to TypeScript, there are a few things that we should do:

- [ ] *Update to NPM5 and update dependencies* The logic here is that we should have the code working with the newest versions of things. NPM5 lock files are nice and `prettier@1.4.0` supports TypeScript. I have a working example of that.
- [ ] *Convert core code to TypeScript* I can work on this. I think the largest difficulty is just getting the build and publish chain correct.
- [ ] *Add a JSX namespace* In order for TSX to work, a JSX namespace must exist with precise types for all of the HTML attributes. I actually think this is the most important work and the one that needs the most help. The elements could be split amongst people.
- [ ] *Add tests and coverage* At this point, tests and coverage which would be awesome

Thoughts?

**Comment by jbucaran** [comment]
@pspeter3 Looking good, but can we also elaborate on the advantages and disadvantages of rewriting the project in TypeScript? 

Also, picodom is advertised as a 1 KB library. Do you think rewriting everything in TypeScript will yield a bundle >1 KB?

**Comment by jbucaran** [comment]
With regards to tests: See #3. 

As for the implementation, we can learn from hyperapp here:

- https://github.com/hyperapp/hyperapp/tree/master/test

**Comment by pspeter3** [comment]
@jbucaran Great questions! My belief is that compiling to `ES6` as a target would maintain the same code size while compiling to lower targets such as `ES3` would increase code size but allow backward compatibility.

**Pros**
- Type safe code which should remove common bugs, especially around null checking
- First class support for other TypeScript projects. Most projects rely on hand written TypeScript definitions as opposed to the definitions generated by other compilers
- Backwards syntax compatibility for ES3 and ES5 if necessary
- Self documenting API

**Cons**
- Slightly more knowledge required to contribute
- Additional build step

**Comment by jbucaran** [comment]
Thanks @pspeter3. Another con is:

- Less visibility (JavaScript projects tend to trend and gain more visibility on GitHub).

However, I'd still like to move forward with this, and see where it lead us.

**Comment by pspeter3** [comment]
Sounds good, I'll work on converting core and then we can add the jsx name space

**Comment by pspeter3** [comment]
Given this library, https://github.com/TylorS167/mostly-dom, is converting worth it?

**Comment by jbucaran** [comment]
@pspeter3 BTW, before a full convert, we could also try introducing [flow](https://flow.org/) or add .ts typings.

**Comment by jbucaran** [comment]
> Given this library, https://github.com/TylorS167/mostly-dom, is converting worth it?

I had a look. Don't see how it affects/relates picodom 🤔

**Comment by pspeter3** [comment]
I agree, that's why I deleted the comment. It just seemed like another TypeScript VDOM technology

**Comment by ngryman** [comment]
I will probably sound like an old grumpy but honestly I don't see any point in using Typescript for such a project, and more generally I don't understand why all the fuzz around it.

I won't start a whole debate here, but JavaScript is what it is: a multi-paradigm language (functional / imperative) leveraging OLOO. It's not an OO language and even if ES6 *sadly* brings `class`, it will never be. It has its advantages and disadvantages, but once you've embraced / mastered it, it's extremely powerful and any attempt to twist it so it looks like Java/C# is just a way to ease those developers transition to the Web platform IMO. But it also prevents them to **really** learn JavaScript and its strengths.
Plus, the nerd in me would say it's not an open standard so it's not made to last. ESNext will.

The only advantage I can see in using Typescript would be static type checking (which can be achieved by other means). For a 10k+ LOC project with dozen of developers collaborating it would make sense, as humans make errors and type checking avoids a bunch of them. But for such a small, focused, performance-driven project, I don't see any advantage, except verbosity.

I don't mean to offend anyone here, those are my opinions and I hope you don't take anything personally @pspeter3.

If you need type definitions, let's just add them aside no?

**Comment by jbucaran** [comment]
I agree with @ngryman. So, to make the cake we will need the following ingredients:

- Static type checking (Flow?)
- Type definitions (typings.json, *.d.ts)

@pspeter3 Would you still be interested in collaborating in picodom if we call off the Typescript rewrite?

**Comment by pspeter3** [comment]
While I disagree with your reasoning about the costs and benefits, I respect your decision and appreciate your honest and thoughtful viewpoint. I personally am not very motivated to work on the type definitions. My experience from maintaining the React type definitions and working with other virtual DOM implementations is that the type definitions easily get out of sync with the codebase. The largest benefit I was hoping for was to have that not be possible.

Thank you once again!

**Comment by jbucaran** [comment]
@pspeter3 I agree with you on the type definitions, and I would wait until things are more stable (stable atm if you ask me though). What about flow? 

> While I disagree with your reasoning about the costs and benefits...

I'm not an expert, so I'd love to hear your reply to @ngryman's comments. We're all learning here. I'm learning.

**Comment by ngryman** [comment]
> I'm not an expert, so I'd love to hear your reply to @ngryman's comments. We're all learning here. I'm learning.

True, and I'd like to hear if I've missed something.

Again I don't really want to debate if X is better than Y, that's not the point. But if you have a strong experience with Typescript (which I don't) and you see real advantages that I failed to see, I'm totally open and curious to get that knowledge.

**Comment by pspeter3** [comment]
I think the biggest point of contention is that TypeScript encourages you to write code in a certain way. TypeScript is a super set of JavaScript so the code can be nearly identical, see the examples below. While I agree with TypeScript not being an open standard, there is talk of adding type annotations to ES7, and it is always possible to compile the TypeScript code to JavaScript and delete the original TypeScript.

With regards to benefits, the benefits are the easy type definitions and the ability to catch bugs. For example, the compiler points out that we have not handled the case of recursive components in the `h` function. _Note: I may have just misunderstood the `h` function so it is possible it was handled correctly elsewhere_

#### `h.ts`

```ts
export type Primitive = string | number | boolean;

export type Child = VElement<string, {}> | Primitive | null;

export type Children = Child[];

export interface VElement<T extends string, D> {
    tag: T;
    data: D;
    children: Children;
}

export type Fragment = Child | Child[];

export type VNode<T extends string, D> = VElement<T, D> | Component<D>;

export interface Component<D> {
    (data: D, children: Children): VNode<string, {}>;
}

export function h<T extends string, D>(tag: T | Component<D>, data: D, ...stack: Fragment[]): VElement<string, {}> {
    let node: Fragment;
    const children: Children = [];
    while (stack.length) {
        node = stack.pop();
        if (Array.isArray(node)) {
            for (let i = node.length; i--;) {
                stack[stack.length] = node[i];
            }
        } else if (node !== null && node !== true && node !== false) {
            if (typeof node === "number") {
                node = node + "";
            }
            children[children.length] = node
        }
    }

    return typeof tag === "string"
        ? { tag, data, children }
        : tag(data, children);
}
```

#### Generated `h.js`

```js
export function h(tag, data) {
    var stack = [];
    for (var _i = 2; _i < arguments.length; _i++) {
        stack[_i - 2] = arguments[_i];
    }
    var node;
    var children = [];
    while (stack.length) {
        node = stack.pop();
        if (Array.isArray(node)) {
            for (var i = node.length; i--;) {
                stack[stack.length] = node[i];
            }
        }
        else if (node !== null && node !== true && node !== false) {
            if (typeof node === "number") {
                node = node + "";
            }
            children[children.length] = node;
        }
    }
    return (typeof tag === "string"
        ? { tag: tag, data: data, children: children }
        : tag(data, children));
}
```

#### Original `h.js`

```js
export function h(tag, data) {
  var node
  var stack = []
  var children = []

  for (var i = arguments.length; i-- > 2; ) {
    stack[stack.length] = arguments[i]
  }

  while (stack.length) {
    if (Array.isArray((node = stack.pop()))) {
      for (var i = node.length; i--; ) {
        stack[stack.length] = node[i]
      }
    } else if (node != null && node !== true && node !== false) {
      if (typeof node === "number") {
        node = node + ""
      }
      children[children.length] = node
    }
  }

  return typeof tag === "string"
    ? {
        tag: tag,
        data: data || {},
        children: children
      }
    : tag(data, children)
}
```

**Comment by ngryman** [comment]
@pspeter3 Thanks for the writeup and the precisions.

What I like in `h.ts` is that with type definitions, it's self documented and brings type checking goodness for users (even if I still find this quite superfluous in a project like this).
The fact that it catches bugs is not really an argument for me as a good test suite does very well the job (even way better) if well written of course.

What I don't like is that `h.ts` is verbose, constraints the user to use a predefined set of types (what if a future plugin wants to add a custom property to nodes or use different kind of `node.data` or whatever?). We'll end up with really complex type definitions to make things lax (like I saw in several other projects) totally defeating the purpose of self-documentation. I strongly prefer a clear and well written JSDoc, than generics everywhere.

`h` just needs that a node has a given *shape*, not a precise topology and type definitions. Using type definitions here makes me feel we are writing explicitly and loudly what's implicit or some times does not even matter. For an AST parser it would be another story though as there are a large variety of nodes and a spec to follow, Typescript would make more sense there IMO.

At the end of the day writing this in Typescript or vanilla JavaScript is only a matter of taste. Some developers like things to be explicitly written, others (me) prefer things to be KISS. It's like the old war between convention / configuration, nobody wins, nobody loses, you just choose what you feel comfortable with.

So @jbucaran, it's your call 👍

**Comment by jbucaran** [comment]
I'd like to keep this issue open and hope to get more feedback from other people.

**Comment by leo-shopify** [comment]
You could also use the [jsdoc style type annotations](https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript) along with `--allowJs` to keep the source files as standard js syntax.
A very [simple example](https://github.com/leo-shopify/typescript-trial) to illustrate.
I haven't used it yet so I don't know if it works as advertised or not.

**Comment by pspeter3** [comment]
Hmm, that actually might be the best option if it can generate DTS files.

**Comment by leo-shopify** [comment]
I don't think d.ts files can be extracted from .js files with jsdoc annotations.

**Comment by pspeter3** [comment]
Oh too bad.

**Comment by ngryman** [comment]
@leo-shopify Thanks for the link! I think it is mostly useful if you are mixing TypeScript / JS. In our case, if we want only want type checking, other tools like Flow might a good option as they are dedicated to that particular job. What do you think?

@pspeter3 The more I think about this issue, the more I think you could provide a type declaration file. I know you mentioned you won't be interested in maintaining it (and I understand your point). But `picodom` has a very small API surface, a `h` signature is pretty much written in the stone. Most changed will be related to internal stuff. What do you think?

**Comment by leo-shopify** [comment]
@ngryman, yes, the gradual option is more beneficial in larger untyped code bases.
If the trade offs between the two, from a developer's perspective, mostly come down to preference, I'd choose based on benefits to the users. It seems to me that typescript is evolving faster and is gaining larger adoption. I'd provably choose typescript today. Having said that, picodom is so small that even making the "wrong" choice doesn't seem that costly.

**Comment by pspeter3** [comment]
@ngryman I'd be happy to add the DTS file. Would you mind if I also added tests that assert the type definitions are correct?

**Comment by ngryman** [comment]
@pspeter3 I'm a total newbie to TypeScript so if you think it's worth, let's go.

/cc @jbucaran

**Comment by pspeter3** [comment]
Yeah, I think in order of DX it is:

- Correct type definitions
- No type definitions
- Incorrect type definitions

The tests will basically just assert that the type definitions have the right types.

**Comment by jbucaran** [comment]
@pspeter3 Cool! Let's do this. Hope it won't be as complex a HyperApp's typings. 😱:smirk::+1:

**Comment by jbucaran** [comment]
Closing in favor of #17.

**Comment by mindplay-dk** [comment]
In my opinion, there's a big advantage to using Typescript, in terms of code comprehension - type-hints really help with the understanding of the internals of the codebase; rather than increasing the learning curve, type-hints provide IDE support, making it easier to navigate and inspect the code.

While I understand that using Typescript might create a barrier for those who don't want to learn it, code with no inline documentation (mainly type-hints) can be really hard to absorb. I've attempted to read the 200 or so lines of code numerous times now, and still most of it is a black box to me.

The real advantage of using a small library such as this one, is not about whether the library is 1KB or 2KB - a typical network package is ~1500 bytes, and the practical difference between 1 or 2 network packages, when you have images etc. taking up hundred of packages during the same request, is rather moot in this day and age.

The important difference of using a minimalist library, is your ability to actually understand what you're using. Now, if *most* people don't get that, because the code is too difficult to read, we're not getting the full advantage of using a small library.

If you don't want to use Typescript, please consider using something else, like flow or js-doc to fully document the internals of the codebase.

Though, in my personal opinion, flow (and to some extent js-doc) come with about the same amount of learning curve in terms of syntax and tools - only with proprietary syntax hidden in doc-blocks, and less powerful IDE support. If the type-hints in Typescript are a distraction to some, they can read the output JS, which would be identical to what you have now - and with flow or js-doc, you'd have to "compile" the JS to validate and strip type-hints from the output, so the process and overhead is really much the same.

I'd also encourage you to use more idiomatic JS and avoid garbling the code to save bytes - working with "minified" code at design-time saves you literally almost no bandwidth in practice, and really gets in the way of comprehension, contributions, refactoring, etc.

You've done an absolutely tremendous job with this library, and I'm really excited to dig into this! :-)

But it would be so much more accesible if you would add inline type-hints and documentation, and unpack your "minified" statements to make the code more readable.

I'd love to help :-)

I could certainly help with the latter, making the code more idiomatic and readable, but I can't really help with the type-hinting, since I'd have real difficulty saying whether I've understood all of it correctly.

**Comment by JorgeBucaran** [comment]
> @mindplay-dk The important difference of using a minimalist library, is your ability to actually understand what you're using. Now, if most people don't get that, because the code is too difficult to read, we're not getting the full advantage of using a small library.

You hit the nail on the head. 💅🔨 

That's the whole point of the 1 KB tagline. I am not saying my library downloads faster, and anyone who thought it was about that missed the forest for the trees.

> If you don't want to use Typescript, please consider using something else, like flow or js-doc to fully document the internals of the codebase.

Yes, I know, but my focus has always been Hyperapp. I said no before, but I am not as strongly opinionated about Picodom as I am about Hyperapp, so come to think about it again, I could rewrite Picodom in TypeScript as a way to learn TypeScript! 🤔 

The beauty of picodom is that it needs not worry about state management, making development much easier than Hyperapp.

**Comment by mindplay-dk** [comment]
I assumed you were very concerned about the package size based on your previous comment

> Also, picodom is advertised as a 1 KB library and that is one of the project's main appeals. Do you know if rewriting everything in TypeScript could yield a bundle size >1 KB?

I took this as you being concerned that a valid Typescript version of the source would be slightly larger, because you might not be able to use some of the non-type-safe (non-idiomatic) shorthand expressions, e.g. assignments inside expressions, and `x && y()` rather than `if (x) { y() }`, etc. which some developers use as a means of saving bytes.

If your first concern is not about saving bytes, then I would be glad to help at least with unfolding some of the compressed code to simpler and more idiomatic code, if you'd like? That will likely make it much easier to port to Typescript or type-hinting with doc-blocks.

If your concern was that compiled Typescript code is somehow larger than plain JS, don't worry, it's not - of course the Typescript code has some longer lines due to the type-hints, but compared with doc-blocks, it's a lot shorter, and the compiled output (for code like this) is the same as the plain JS with no type-hints...

**Comment by JorgeBucaran** [comment]
Yes!

**Comment by mindplay-dk** [comment]
@JorgeBucaran here's where I am with my Typescript rewrite:

https://bitbucket.org/mindplaydk/veedom/src

There's a bunch of noisy console output at this time, as I'm still evaluating some things by merely reading through the order of events, but a lot of tests are passing now, including tests for `onremove` and `ondestroy` - although I haven't tested for the loss of ordering yet, which may affect this implementation too.

This is *very* rough still - I'm just posting it in case you find some useful (or avoidable) ideas in the implementation or something :-)

**Comment by JorgeBucaran** [comment]
Awesome! 👍 

By the way, I'd like to combine onremove and ondestroy into a single event (without any functionality loss) like I did with hyperapp.

**Comment by mindplay-dk** [comment]
> I'd like to combine onremove and ondestroy into a single event

Yeah, I saw that, did I comment? I don't understand how that would work.

If you have only one event that always gets fired, how do you know whether to trigger animation or clean-up when that event fires? It seems like, if you have only one event, and the same element needs to respond both to removal (with animation) and needs to clean something up, you're going to trigger unnecessary animation of elements when they actually get destroyed. I can't help but think you're over-simplifying here? Direct removal of a child-node is not the same thing as indirect removal of entire ranges of child-nodes. For example, if you have an animation for list items getting removed, but the app also has some function that toggles whether that list is visible at all. I don't understand how one event could be enough?

**Comment by JorgeBucaran** [comment]
https://github.com/hyperapp/hyperapp/blob/f9ad50ff8f89be0723ef1bdaf3350536dd7d8f11/src/index.js#L192

@mindplay-dk What do you mean? You either want to trigger an animation or clean-up resources and `done` should only be called on the top-most onremove, since we are not going to call `removeChild` on child elements.

**Comment by mindplay-dk** [comment]
The last cycle of this test [here](https://bitbucket.org/mindplaydk/veedom/src/424b8c8020b3ec2eea077255d3730a8a454e303f/src/test.tsx?at=master&fileviewer=file-view-default#test.tsx-248) - I expect the remove notification for the parent div only, but I expect destroy notifications for the parent *and* child divs.

If you have only one kind of notification, how can you tell if the element is being directly on indirectly removed? (or are you arguing you don't *need* to know?)

**Comment by JorgeBucaran** [comment]
`onremove` is only called for a top-level element and `ondestroy` is called for all the elements.

With a single `onremove`, if I am using `onremove` on a top-level element for animation, I will be calling `done` when the animation or transition is done. If am using it on a child/nested element, that means it's not for animation, but for cleaning up resources, so I don't need to call `done`.

And, of course, `.removeChild` will not be called for child elements (by default).

```js
if (!isChild) parent.removeChild(element)
```

**Comment by mindplay-dk** [comment]
> With a single onremove, if I am using onremove on a top-level element for animation, I will be calling done when the animation or transition is done. If am using it on a child/nested element, that means it's not for animation, but for cleaning up resources, so I don't need to call done.

How will you know which is the case?

For example:

```html
<div class="app">
    <ul class="items">
        <li>...</li>
        <li>...</li>
        <li>...</li>
    </ul>
</div>
```

Let's say every `<li>` contains a date-picker control from a third-party library.

Every `<li>` is going to need an `onremove` handler for the animation that gets triggered for the individual items in the list. With a unified `onremove`, that's fine - I can clean up the date-picker instance when the animation finishes.

But every `<li>` is also going to need an `ondestroy` handler for the case where the entire `<ul>` gets toggled on and off. In this case, there's no animation. But we still need to clean up all the date-pickers. With a unified `onremove`, how are you able to tell the difference?

For the removal of list items, animation and then clean-up should be triggered - you've covered that case. For the removal of the entire list, only the clean-up should be triggered - that doesn't seem possible with only one life-cycle event.

**Comment by JorgeBucaran** [comment]
@mindplay-dk I see what you are saying now, you are right! 🙃  

Okay, what about this: pass a second argument to the function `(element, isRoot)` that tells you whether the element is being directly removed

```js
(element, isRoot) => {
  element.datePicker.clean()
  if (isRoot) {
    return done => fadeout(element).then(done)
  }
}
```

**Comment by mindplay-dk** [comment]
> pass a second argument to the function

I'd say that's a symptom of complecting two concerns into one.

The resulting complexity will spread and generate more if-statements and/or inline functions, making it harder to reason about these handlers - your example doesn't work, you're destroying the date-picker too soon: it'll pop out of view before the animation starts.

A working example might look more like this:

```ts
(element, isRoot) => {
  if (isRoot) {
    return done => fadeout(element).then(() => {
      element.datePicker.clean()
      done()
    })
  } else {
    element.datePicker.clean()
  }
}
```

If the clean-up logic is more than a single line/statement, you'll likely need an inline function too:

```ts
(element, isRoot) => {
  if (isRoot) {
    return done => fadeout(element).then(() => {
      cleanup()
      done()
    })
  } else {
    cleanup()
  }

  function cleanup() {
    element.datePicker.clean()
    // ... whatever else
  }
}
```

In my opinion, this is a clear case of conflating multiple concerns - while a lower number of life-cycle events may seem "simpler", this is somewhat of a deception, as that one life-cycle event has to support *all* the use-cases that could have been handled independently with two events.

Why the resistance to separating two concerns that can be cleanly separated?

**Comment by mindplay-dk** [comment]
Meanwhile, back in the jungle: I added the order preservation test for deferred removals to my implementation, and, it suffers from exactly the same problem - I'm stuck with the exact same dead ends as with picodom, and still no closer to solving it either for picodom or my own patcher 🙄

**Comment by JorgeBucaran** [comment]
So, something like this is the cleaner alternative in your opinion.

```js
function cleanup(element) {
  element.datePicker.clean()
  // ... whatever else
}

onremove: element => done =>
  fadeout(element).then(() => {
    cleanup(element)
    done()
  })

ondestroy: element => {
  cleanup(element)
}
```

**Comment by JorgeBucaran** [comment]
And for comparison, here is mine.

```js
function cleanup(element) {
  element.datePicker.clean()
  // ... whatever else
}

onremove = (element, isRoot) =>
  isRoot
    ? done =>
        fadeout(element).then(() => {
          cleanup(element)
          done()
        })
    : cleanup(element)
```

**Comment by JorgeBucaran** [comment]
Or this

```jsx
function cleanup(element, done) {
  element.datePicker.clean()
  // ... whatever else
  if (done) done()
}

onremove: (element, isRoot) =>
  isRoot
    ? done => fadeout(element).then(() => cleanup(element, done))
    : cleanup(element)
```

**Comment by mindplay-dk** [comment]
No, just this.

```ts
onremove: element => done =>
  fadeout(element).then(done)

ondestroy: element =>
  element.datePicker.clean()
```

Pretty clean and simple? :-)

**Comment by JorgeBucaran** [comment]
@mindplay-dk You are totally right. I won't proceed with my plan and I will bring back ondestroy to hyperapp. Thanks! 👍

**Comment by JorgeBucaran** [comment]
@mindplay-dk I just realized we had this entire convo on the wrong issue! Too late now! 😆

**Comment by mindplay-dk** [comment]
@JorgeBucaran haha, whoops 🙄

**Comment by SteveALee** [comment]
A couple of points 're "original" topics :)

* typescript gives a fantastic editor experience with completion etc. Vs code uses the typescript compiler for javascript so can infer a lot but code written in ts is even better.
* I like ts compared to flow as they have worked really hard to keep it close to js with types that get stripped.  There are new language features but this mostly means the run time library is just JS and the package adds typings which are ignored by JS users. Win win.

**Comment by JorgeBucaran** [comment]
@SteveALee TS > Flow totally.

**Comment by SteveALee** [comment]
That said. For sucj a small project adding manually maontained typings gives almost all the advantages for users, if not the static typing for the lib devs.

**Comment by JorgeBucaran** [comment]
@SteveALee Yes, sure and I am going to rewrite Picodom in TS! That's why I reopened :)

I hope that will be how Picodom can start to evolve away from Hyperapp into its own thing. 🙏

**Comment by mindplay-dk** [comment]
@jorgebucaran I started (yet another) rewrite in Typescript, and once again, I gave up.

https://bitbucket.org/mindplaydk/domsync

I wish you'd collaborate with me on this, since apparently I'm too stupid to grasp the `updateChildren()` idea and get it right 🙄 

This time around, I've spent zero time on the external types - but I learned some important things about the internal type-hints: `make` is my factory-function, and the accepts JSX "input", which is distinct from actual JSX elements, because we can count on the `make` function to weed out deeply nested arrays and `true`, `false`, `""`, `null` and `undefined`. This means we can count on every child being either a `JSX.Element` or `string`, which greatly simplifies internal typing.

I've adopted the `(vnode: JSXNode, target?: Node): Node` signature that we settled on, which allows DOM nodes to be patched or replaced directly.

I've once again gone the route of attaching meta-data to the DOM nodes, where `__type` serves as an indication (both on `Element` and `Text` nodes) that the nodes is *managed* - this should enable managed nodes to live side-by-side with unmanaged nodes, which is probably a plus, but the main purpose of this is to eventually support life-cycle events, such that deferred removals can be implemented by simply removing the `__type` property, allowing nodes to stay in place and maintain order, even while taking multiple update passes around their siblings.

Hoping to explain `updateChildren()` to myself, this is heavily documented, but apparently I still can't understand how this is supposed to work - even if the descriptions make sense, the idea itself doesn't seem to, but the rest of it is a good starting point, I think.

There's a basic, failing test for preservation of keyed elements, which should help move this along - likely by rewriting all or most of `updateChildren()` since the idea is probably all wrong. And then there's a more aggressive test for (seeded random) reordering, in which a number of keyed elements are shuffled a set number of times, which should ensure this covers every conceivable edge-case.

Well, I'm hoping you or somebody else will pick up and try to move this forward... 10+ hours of this today, and I'm completely spent 🙄💤

**Comment by jorgebucaran** [comment]
@mindplay-dk The company I work at recently switched to Hyperapp+TypeScript, so I've been learning TS in practice. Now, the bad news is I feel less enthusiastic about TS than I did 2 months ago. Maybe _I_ am too stupid to grasp the importance of it, but I feel TS just doesn't make sense for small code bases like Ultradom. I hope I am not alone in this sentiment.

Are you having trouble understanding how patch/updateChildren work? Do you mean how the reconciliation algorithm works? Just clarifying.

**Comment by mindplay-dk** [comment]
> I feel TS just doesn't make sense for small code bases like Ultradom

YMMV.

For me, just being able to actually change the code and visually see the impact (in an IDE like VS Code) is enough to make it more than worth while.

While it's not a lot of code, it's a really *critical* small piece of code - it's going to be the code that underpins *all* of your UI, and therefore it's critical that it's correct, in the strictest possible sense of the word. Accepting a simple one-line PR, for example, the consequences throughout the code aren't always obvious.

What I've set out to do with this attempt, is clarify what exists, what's acceptable, when and where, which is not something you get from plain JS at all. Just having code that formally documents the types and function singatures makes the code much easier to change.

Like I said, YMMV - but I'll just say, I've known a lot of people by now who were initially very sceptical of the benefits, but it dawns on them eventually, usually after a few months. Maybe you're right on the cusp of it and you don't realize it yet? Attempting to build this with complete type-safety might just be the experience that pushes you over the edge ;-)

On a personal note, some people end up not liking TS at all - in my experience, these are typically the sort of people who have an *excellent* capacity for memorization. I suspect you may be that type of person? Your original codebase had practically zero comments, and it took me months to absorb all the details. I have a great capacity for learning, but I have practically *zero* capacity for memorization, so I strongly prefer code that is fully type-hinted, so you can more easily view and explore the code in an IDE.

On a more practical note, writing this in TS ensures your `.d.ts` is as accurate as your code 👍 

> Are you having trouble understanding how patch/updateChildren work? Do you mean how the reconciliation algorithm works?

Yeah, but I'm going to leave it alone for at least a week now, because it starts to interfere with my dreams - I wake up way too early thinking about and I lose sleep.

I'll probably bench it for now and take another stab at it in a week or so ;-)

**Comment by SteveALee** [comment]
From my experience the sweet spot with ts is not to type everything but just the interfaces. These may be public or internal but they are the points were dependencies need to be explicit so you know when they are broken. Type script makes fully definging flexible JS interfaces pretty easy in most cases. Especially with its"generics".

I'd say it's worth persevering when you have more energy. Perhaps look at examples like cyclejs.

**Comment by pspeter3** [comment]
> On a more practical note, writing this in TS ensures your .d.ts is as accurate as your code

That's my favorite piece of all of this.

**Comment by dancespiele** [comment]
@mindplay-dk testing my example project I realized that we need to improve the types. When I have time I will work on this and I will make a PR and we can discuss about this. Also I would like to implement ts-linter to check the style code for the future changes, if you make a PR earlier then perfect I can check that.
@jorgebucaran In my case typescript help me to think previously when I'm working in new implementations because I have to describe all the class and functions and in the end I don't have to do a lot try and fail :) . Since I know typescript always I want to work with it.

**Comment by jorgebucaran** [comment]
@dancespiele https://github.com/jorgebucaran/ultradom/issues/7#issuecomment-372190490

**Comment by jorgebucaran** [comment]
@pspeter3 @mindplay-dk I gave it another shot and rewrote it in TS (managed to get tsc to compile), but it was PITA to set up the tests with Jest (it didn't work flawlessly using the current config) so I just gave up.

**Comment by pspeter3** [comment]
Would it help if I set up the configuration for you?

**Comment by jorgebucaran** [comment]
@pspeter3 It would. I am curious about the options we have to test with TS. 🙏

**Comment by mindplay-dk** [comment]
I successfully used `tape` with `jsdom` with full type-checking in [this project](https://bitbucket.org/mindplaydk/domsync/src/master/). (I generally avoid big complicated test-frameworks, but if I needed to run tests in a headless browser environment, I'd probably give Jest a shot as well. For my own purposes `jsdom` was fine.)

**Comment by pspeter3** [comment]
For what it's worth, jest is mostly a wrapper around Jasmine/JsDOM/NYC.

**Comment by jorgebucaran** [comment]
@pspeter3 Do I need another package to use Jest with TS? That's where I got stuck.

**Comment by SteveALee** [comment]
Any use? https://github.com/facebook/jest/tree/master/examples/typescript

**Comment by pspeter3** [comment]
You need to have ts-jest too which will do in memory compilation. Is there a branch I can work off?

**Comment by jorgebucaran** [comment]
> You need to have ts-jest too...

Hmm, yeah, I saw it, and I figured there must be a better way so I looked elsewhere, found nothing and eventually gave up.

**Comment by pspeter3** [comment]
Well you can either compile the TypeScript first using the TypeScript compiler or you can register a transform for jest. Do you have a preference between the two?

**Comment by pspeter3** [comment]
It is merely a compiler. Most frameworks support TS with minimal effort/configuration.

**Comment by jorgebucaran** [comment]
@pspeter3 Do you know any TS projects using jest with a minimal configuration? I'd love to have a peek. I still haven't completely given up on this.

**Comment by pspeter3** [comment]
Here is an outdated `package.json`

```js
{
  "name": "example",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "coverage": "codecov --file=coverage/coverage-final.json",
    "fmt": "tslint --fix --force --project tsconfig.json && prettier --write 'src/**/*'",
    "lint": "tslint --project tsconfig.json",
    "spec": "jest",
    "test": "npm run lint && npm run style && npm run spec"
  },
  "dependencies": {
    "tslib": "^1.9.0"
  },
  "devDependencies": {
    "@types/jest": "^22.2.0",
    "codecov": "^3.0.0",
    "jest": "^22.4.2",
    "prettier": "^1.11.1",
    "ts-jest": "^22.4.1",
    "tslint": "^5.9.1",
    "typescript": "^2.7.2"
  },
  "jest": {
    "collectCoverage": true,
    "globals": {
      "ts-jest": {
        "enableTsDiagnostics": true,
        "skipBabel": true
      }
    },
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js"
    ],
    "testRegex": "_spec\\.(ts|tsx)$",
    "testEnvironment": "node",
    "transform": {
      "^.+\\.tsx?$": "ts-jest"
    }
  },
  "prettier": {
    "printWidth": 100,
    "tabWidth": 4,
    "trailingComma": "all"
  }
}
```

**Comment by jorgebucaran** [comment]
Well, sounds like a holy mess.

**Comment by mindplay-dk** [comment]
@jorgebucaran relax 😄 it's not too bad... and, counterpoint: the mess is inherent to JS and was there the whole time - TS at least brings some degree of structure to that mess. (that's kind of it's whole reason for existing in the first place.)

**Comment by mindplay-dk** [comment]
> I wanted to accomplish this with as few deps as possible

Then you should have picked `tape` and not `jest` ;-)

Joking aside, this doesn't really add a dependency - this just adds type-checking for `jest`, which is a single `.d.ts` file. This is completely normal when using plain JS packages in TS - although a growing number of packages ship with a built-in `.d.ts`, `jest` currently does not.

> One reason why I wanted to revisit this was to eliminate the .d.ts file, so that it would be fewer files.

That has nothing to do with this issue - you will still accomplish that, by using the `declarations` directive in `tsconfig.json` to automatically generate *your* `.d.ts` and ship it with your package. Typescript users installing your package *won't* need to get the type-declarations via `@types`. You're winning 😄
